server:
  port: 8080

spring:
  application:
    name: UserManagerService
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: dev
        group:  authority
    profiles:
      active: dev
  shardingsphere:
    datasource:
      names: ds0, ds1, ds2
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/authority_users_db_0?serverTimezone=UTC&useSSL=false
        username: root
        password: 2004zyta
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/authority_users_db_1?serverTimezone=UTC&useSSL=false
        username: root
        password: 2004zyta
      ds2:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/authority_common?serverTimezone=UTC&useSSL=false
          username: root
          password: 2004zyta

    rules:
      sharding:
        default-data-source-name: ds2
        tables:
          users:
            actual-data-nodes: ds$->{0..1}.users_$->{0..4}
            table-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: user_inline
            key-generate-strategy:
              column: user_id
              key-generator-name: snowflake

        default-database-strategy:
          standard:
            sharding-column: user_id
            sharding-algorithm-name: database_inline

        sharding-algorithms:
          user_inline:
            type: INLINE
            props:
              algorithm-expression: users_$->{user_id % 5}
          database_inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{user_id % 2}

        key-generators:
          snowflake:
            type: SNOWFLAKE
  redis:
    host: 192.168.253.153
    port: 6379
    password: 2004zyta
  rabbitmq:
    host: 192.168.253.153       # 或你的RabbitMQ地址
    port: 5672
    username: guest
    password: guest

seata:
  enabled: true
  enable-auto-data-source-proxy: false  # 禁用自动代理数据源，解决报错
  application-id: ${spring.application.name}
  tx-service-group: user-manager-service-group
  service:
    vgroup-mapping:
      user-manager-service-group: default
      permission-service-group: default
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: dev
      group: SEATA_GROUP
      username: nacos
      password: nacos


### Feign 配置
#feign:
#  client:
#    config:
#      default:
#        connect-timeout: 20000
#        read-timeout: 120000
