server:
  port: 8081

spring:
  application:
    name: PermissionService
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: dev
        group:  authority
    profiles:
      active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authority_permission?serverTimezone=UTC&useSSL=false
    username: root
    password: 2004zyta
seata:
  enabled: true
  application-id: ${spring.application.name}        # permission-service
  tx-service-group: permission-service-group         # 事务组名（和user服务对应）
  service:
    vgroup-mapping:
      user-manager-service-group: default            # 与user服务共享默认集群
      permission-service-group: default              # 自己的事务组映射
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: dev
      group: SEATA_GROUP
      username: nacos
      password: nacos
