server:
  port: 8081

spring:
  application:
    name: PermissionService
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: dev
        group:  authority
    profiles:
      active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authority_permission?serverTimezone=UTC&useSSL=false
    username: root
    password: 2004zyta